### ISSUE TITLE
myukkurivoice-vendor.gitをクローンできない

### ISSUE THREAD

**Issue by anatawa12** [taku-o/myukkurivoice#179]
中身を読んだりしてみたいと思ってcloneとsubmoduleの初期化をしようとしたらmyukkurivoice-vendor.gitがクローンできませんでした。

**Comment by taku-o** [comment]
myukkurivoice-vendor.gitは、パブリックに配布不能なライブラリと
ライセンスキーが入っているため、privateなレポジトリになっています。
https://github.com/taku-o/myukkurivoice/blob/master/docs/development.md
```
  vendor
    +-- AquesTalk.framework       AquesTalkフレームワーク
    +-- AquesTalk2.framework      AquesTalkフレームワーク
    +-- AquesTalk10.framework     AquesTalkフレームワーク
    +-- AqKanji2Koe.framework     AquesTalkフレームワーク
    +-- AqUsrDic.framework        AquesTalkフレームワーク
    +-- phont                     AquesTalk音声設定
    +-- aq_dic_large              AquesTalk辞書
    +-- aq_dic_large/aq_user.csv  AquesTalkユーザー辞書のマスターデータCSV
    +-- maquestalk1               AquesTalk1フレームワークbridge
    +-- secret                    AquesTalk10ライセンスキー取得コード
```

さて、このMYukkuriVoiceを、開発ライセンスを持たない状態で、ソースから作って実行する方法ですが
もっとも正攻法なやり方は、AquesTalkから体験版を持ってくることです。

**Comment by anatawa12** [comment]
わかりました。なんとなくlicenseかなと思ったのですがそうだったのですね。わかりました。
(勝手にしていいのかしっかり理解してないですが)解決したのでcloseします
