### ISSUE TITLE
macOS High Sierraの動作確認

### ISSUE THREAD

**Issue by taku-o** [taku-o/myukkurivoice#44]
動作確認できるMacが無い。
今使っていないMacも持ってないこともないけれど。

**Comment by akatsuki** [comment]
HighSierraにて動作を確認しました。
おおよそ正常に動作しております。

**Comment by taku-o** [comment]
good.
issueはまだ開けておく

**Comment by taku-o** [comment]
よく考えると、自分で確認するまで、はいそーですかとissueを閉じれない気がする。

**Comment by taku-o** [comment]
だいぶ前よりHigh Sierraで動作確認。closeする
